name: Your Workflow Name
run-name: Linear Update App Running 🚀

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - shell: bash
      run: |
        echo "Current working directory is"
        pwd
        ls
    - name: Lint with flake8
      shall: bash
      run: |
        cd src
        python update_linear_status.py
